CREATE TABLE [HABILITATION].[HAB_USER] (
    [C_USER]   VARCHAR (20)   NOT NULL,
    [C_PWD]    VARCHAR (50)   NOT NULL,
    [I_TIEPHY]    NUMERIC (10)   NULL,
    [L_NOM]    VARCHAR (50)   NOT NULL,
    [L_PRENOM] VARCHAR (50)   NOT NULL,
    [L_EMAIL]  VARCHAR (100)  NOT NULL,
    [C_ETAT]   CHAR (1)       NOT NULL,
    [D_DEB]    DATETIME       NULL,
    [D_FIN]    DATETIME       NULL,
    [N_ETP]    NUMERIC (3, 2) CONSTRAINT [DF_N_ETP] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_T_USER] PRIMARY KEY CLUSTERED ([C_USER] ASC)
)
