CREATE TABLE [HABILITATION].[HAB_USER_MEMBER]
(
	[I_TIEPHY] NUMERIC(10) NOT NULL PRIMARY KEY, 
    [L_EMAIL] NVARCHAR(100) NOT NULL
)
go
CREATE NONCLUSTERED INDEX [HAB_USER_MEMBER_IDX_TIEPHY_EMAIL]
    ON [HABILITATION].[HAB_USER_MEMBER]([I_TIEPHY] ASC, [L_EMAIL] ASC);
GO