CREATE TABLE [HABILITATION].[HAB_DROITS] (
    [I_PROFIL]  NUMERIC (8) NOT NULL,
    [I_FONC]    NUMERIC (8) NOT NULL,
    [B_CONSULT] BIT         DEFAULT ((1)) NOT NULL,
    [B_CREATE]  BIT         DEFAULT ((1)) NOT NULL,
    [B_UPDATE]  BIT         DEFAULT ((1)) NOT NULL,
    [B_DELETE]  BIT         DEFAULT ((1)) NOT NULL,
    [B_EXEC]    BIT         DEFAULT ((1)) NOT NULL,
    [C_SPEC]    CHAR (5)    NULL,
    CONSTRAINT [PK_T_DROITS] PRIMARY KEY CLUSTERED ([I_FONC] ASC, [I_PROFIL] ASC),
    CONSTRAINT [FK_DROITS_FONCTIONNALITE] FOREIGN KEY ([I_FONC]) REFERENCES [HABILITATION].[HAB_FONCTIONNALITE] ([I_FONC]),
    CONSTRAINT [FK_DROITS_PROFIL] FOREIGN KEY ([I_PROFIL]) REFERENCES [HABILITATION].[HAB_PROFIL] ([I_PROFIL])
)
