CREATE TABLE [HABILITATION].[HAB_HABILITATION] (
    [C_USER]   VARCHAR (20) NOT NULL,
    [I_PROFIL] NUMERIC (8)  NOT NULL,
    CONSTRAINT [PK_T_HABILITATION] PRIMARY KEY CLUSTERED ([I_PROFIL] ASC, [C_USER] ASC),
    CONSTRAINT [FK_HABILITATION_PROFIL] FOREIGN KEY ([I_PROFIL]) REFERENCES [HABILITATION].[HAB_PROFIL] ([I_PROFIL]),
    CONSTRAINT [FK_HABILITATION_USER] FOREIGN KEY ([C_USER]) REFERENCES [HABILITATION].[HAB_USER] ([C_USER])
)