//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InternalMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.InternalMessages", typeof(InternalMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La donnée de configuration &apos;{0}&apos; comporte une valeur incorrecte : &apos;{1}&apos;..
        /// </summary>
        public static string ApplicationConfigurationBadValue {
            get {
                return ResourceManager.GetString("ApplicationConfigurationBadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La chaîne de connexion &apos;{0}&apos; est introuvable dans le fichier de configuration..
        /// </summary>
        public static string ApplicationConfigurationMissingConnectionString {
            get {
                return ResourceManager.GetString("ApplicationConfigurationMissingConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La donnée de configuration &apos;{0}&apos; est introuvable dans le fichier de configuration..
        /// </summary>
        public static string ApplicationConfigurationMissingSetting {
            get {
                return ResourceManager.GetString("ApplicationConfigurationMissingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il faut appeler UseHttpConfiguration avant d&apos;appeler cette méthode..
        /// </summary>
        public static string CallUseHttpConfigurationFirst {
            get {
                return ResourceManager.GetString("CallUseHttpConfigurationFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event non spécifié.
        /// </summary>
        public static string EventUnknown {
            get {
                return ResourceManager.GetString("EventUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le TraceListener est surchargé..
        /// </summary>
        public static string FrameworkListenerFlooded {
            get {
                return ResourceManager.GetString("FrameworkListenerFlooded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème de configuration du TraceListener : valeur d&apos;attribut incorrecte pour &apos;{0}&apos;..
        /// </summary>
        public static string FrameworkListenerInvalidAttribute {
            get {
                return ResourceManager.GetString("FrameworkListenerInvalidAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème de configuration du TraceListener : valeur d&apos;attribut incorrecte pour &apos;{0}&apos;, utilisation de la valeur par défault &apos;{1}&apos;..
        /// </summary>
        public static string FrameworkListenerInvalidAttributeBackToDefault {
            get {
                return ResourceManager.GetString("FrameworkListenerInvalidAttributeBackToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur d&apos;écriture du TraceListener : &apos;{0}&apos;..
        /// </summary>
        public static string FrameworkListenerLoggingError {
            get {
                return ResourceManager.GetString("FrameworkListenerLoggingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème de configuration du TraceListener : attribut manquant : &apos;{0}&apos;..
        /// </summary>
        public static string FrameworkListenerMissingAttribute {
            get {
                return ResourceManager.GetString("FrameworkListenerMissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème de configuration du TraceListener : configuration introuvable..
        /// </summary>
        public static string FrameworkListenerMissingConfiguration {
            get {
                return ResourceManager.GetString("FrameworkListenerMissingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il faut créer un Tracer avant de pourvoir l&apos;utiliser..
        /// </summary>
        public static string FrameworkTracerNotCreated {
            get {
                return ResourceManager.GetString("FrameworkTracerNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appel de {0}.
        /// </summary>
        public static string MethodCall {
            get {
                return ResourceManager.GetString("MethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La resource demandée n&apos;existe pas..
        /// </summary>
        public static string NotFoundResource {
            get {
                return ResourceManager.GetString("NotFoundResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème de configuration, le cache d&apos;autorisation ne pourra pas être vidé..
        /// </summary>
        public static string ResetCacheAutorisationServiceImpossible {
            get {
                return ResourceManager.GetString("ResetCacheAutorisationServiceImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une réponse a déjà commencé à être envoyée. Comportement innatendu..
        /// </summary>
        public static string ResponseAlreadyStarted {
            get {
                return ResourceManager.GetString("ResponseAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type non spécifié.
        /// </summary>
        public static string TypeUnknown {
            get {
                return ResourceManager.GetString("TypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un utilisateur a tenté de déclencher une opération non autorisée..
        /// </summary>
        public static string UnexpectedUserAction {
            get {
                return ResourceManager.GetString("UnexpectedUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur de validation de la demande s&apos;est produite..
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur de traitement de la demande s&apos;est produite..
        /// </summary>
        public static string WebApiProblemTitle {
            get {
                return ResourceManager.GetString("WebApiProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appel du web service {0}.
        /// </summary>
        public static string WebServiceCall {
            get {
                return ResourceManager.GetString("WebServiceCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réponse du web service {0}.
        /// </summary>
        public static string WebServiceResponse {
            get {
                return ResourceManager.GetString("WebServiceResponse", resourceCulture);
            }
        }
    }
}
