INSERT [HABILITATION].[HAB_PROFIL] ([I_PROFIL], [L_PROFIL], [C_ETAT], [D_DEB], [D_FIN]) 
    VALUES (1, N'Backoffice', N'A', N'2019-01-01T00:00:00.000', NULL);
INSERT [HABILITATION].[HAB_FONCTIONNALITE] ([I_FONC], [L_FONC], [C_ETAT], [D_DEB], [D_FIN], [C_FONC])
    VALUES (1, N'CacheAutorisations', N'A','2019-01-01T00:00:00.000', NULL, N'CACHEAUTOR')
INSERT [HABILITATION].[HAB_DROITS] ([I_PROFIL], [I_FONC], [B_CONSULT], [B_CREATE], [B_UPDATE], [B_DELETE], [B_EXEC], [C_SPEC])
    VALUES (1, 1, 1, 1, 1, 1, 1, N'fh   ')
